/*
 * This source file was generated by PSProject
 */

import XCTest
@testable import App

class KivyThorGamesTests: XCTestCase {
    public static let allTests = [
        ("testExample", testExample),
    ]

    func testExample() {
        XCTAssertTrue(true)
    }
}