from typing import Callable
from kivy.graphics.instructions import RenderContext
from kivy.graphics.texture import Texture
from thorvg_cython.gl_canvas import GlCanvas

class ThorFbo(RenderContext):
    gl_canvas: GlCanvas

    def __init__(
        self,
        gl_canvas: GlCanvas,
        *args,
        size: tuple[int, int] = (1024, 1024),
        clear_color: tuple[float, float, float, float] = (0, 0, 0, 0),
        push_viewport: bool = True,
        with_depthbuffer: bool = False,
        with_stencilbuffer: bool = False,
        texture: Texture | None = None,
        **kwargs,
    ) -> None: ...

    def bind(self) -> None: ...
    def release(self) -> None: ...
    def clear_buffer(self) -> None: ...
    def get_pixel_color(self, wx: int, wy: int) -> tuple[int, int, int, int]: ...
    def add_reload_observer(self, callback: Callable) -> None: ...
    def remove_reload_observer(self, callback: Callable) -> None: ...

    @property
    def size(self) -> tuple[int, int]: ...
    @size.setter
    def size(self, value: tuple[int, int]) -> None: ...

    @property
    def clear_color(self) -> tuple[float, float, float, float]: ...
    @clear_color.setter
    def clear_color(self, value: tuple[float, float, float, float]) -> None: ...

    @property
    def texture(self) -> Texture: ...

    def __enter__(self) -> "ThorFbo": ...
    def __exit__(self, *args) -> None: ...
