[project]
name = "kivy-thor-games"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "psychowasp", email = "psychowaspx@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "kivy==3.0.0.dev0",
    "kivy-thor>=0.1.0",
    "thor-asteroids",
    "thor-ballbreaker",
    "thor-flappy",
    "thorvg-cython>=0.0.5",
]

[project.scripts]
kivy-thor-games = "kivy_thor_games:main"

[build-system]
requires = ["uv_build>=0.11.3,<0.12.0"]
build-backend = "uv_build"


[tool.uv]
find-links = ["../wheelhouse"]

[tool.uv.sources]
thor-flappy = { path = "../games/thor-flappy" }
thor-asteroids = { path = "../games/thor-asteroids" }
thor-ballbreaker = { path = "../games/thor-ballbreaker" }
