[project]
name = "thor-tetris"
version = "0.1.0"
description = "Tetris game with thorvg-cython rendering and pymunk debris physics"
readme = "README.md"
authors = [
    { name = "psychowasp", email = "psychowaspx@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pymunk",
    "thorvg-cython>=0.0.5",
]

[project.scripts]
thor-tetris = "thor_tetris:main"

[build-system]
requires = ["uv_build>=0.11.3,<0.12.0"]
build-backend = "uv_build"
